// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcmUAXZ519B2yjXeGGNso-dAKo61yLzI',
    appId: '1:210330991908:web:998ff22f263eb0f4f847b1',
    messagingSenderId: '210330991908',
    projectId: 'reco-genie-task-e1924',
    authDomain: 'reco-genie-task-e1924.firebaseapp.com',
    storageBucket: 'reco-genie-task-e1924.firebasestorage.app',
    measurementId: 'G-FYEJDB5T4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkB2x-9d07-_hwbTyxLnSV-hZLz-wM7M8',
    appId: '1:210330991908:android:9aeb67cd36b885c4f847b1',
    messagingSenderId: '210330991908',
    projectId: 'reco-genie-task-e1924',
    storageBucket: 'reco-genie-task-e1924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2LUkD9iTPJSKGvld46rhlwVAiZhRNJ4',
    appId: '1:210330991908:ios:901f640e7ac9ec0df847b1',
    messagingSenderId: '210330991908',
    projectId: 'reco-genie-task-e1924',
    storageBucket: 'reco-genie-task-e1924.firebasestorage.app',
    iosBundleId: 'com.example.recoGenieTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2LUkD9iTPJSKGvld46rhlwVAiZhRNJ4',
    appId: '1:210330991908:ios:901f640e7ac9ec0df847b1',
    messagingSenderId: '210330991908',
    projectId: 'reco-genie-task-e1924',
    storageBucket: 'reco-genie-task-e1924.firebasestorage.app',
    iosBundleId: 'com.example.recoGenieTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqcmUAXZ519B2yjXeGGNso-dAKo61yLzI',
    appId: '1:210330991908:web:8dcc9ffce959dba6f847b1',
    messagingSenderId: '210330991908',
    projectId: 'reco-genie-task-e1924',
    authDomain: 'reco-genie-task-e1924.firebaseapp.com',
    storageBucket: 'reco-genie-task-e1924.firebasestorage.app',
    measurementId: 'G-PTV6LQRGJM',
  );
}
